selector = "#picture1"
type = "image"
commands = [ "png(100x200){90,180,270}" ]

[[cloudStorage]]
service = "aws"
bucket = "squared-001"

  [cloudStorage.credential]
  accessKeyId = "**********"
  secretAccessKey = "**********"
  region = "us-west-2"
  sessionToken = "**********"

  [cloudStorage.upload]
  active = false
  localStorage = true
  filename = "picture1.webp"
  all = false
  overwrite = false

  [cloudStorage.download]
  filename = "picture2.png"
  versionId = "12345"
  pathname = "download/images"
  active = false
  overwrite = false
  deleteObject = false

[[cloudStorage]]
service = "azure"
bucket = "squared-002"

  [cloudStorage.credential]
  accountName = "**********"
  accountKey = "**********"
  connectionString = "**********"
  sharedAccessSignature = "**********"

  [cloudStorage.upload]
  pathname = "a/b/c/"
  endpoint = "http://squaredjs.azureedge.net/squared-002"

[[cloudStorage]]
service = "gcloud"
bucket = "squared-003"

  [cloudStorage.credential]
  keyFilename = "./gcloud.json"

  [cloudStorage.admin]
  publicRead = false
  emptyBucket = false
  preservePath = false

  [cloudStorage.upload]
  active = true
  publicRead = false

[[cloudStorage]]
service = "ibm"
bucket = "squared-004"

  [cloudStorage.credential]
  apiKeyId = "**********"
  serviceInstanceId = "**********"
  region = "us-south"
  endpoint = "https://s3.us-south.cloud-object-storage.appdomain.cloud"

[[cloudStorage]]
service = "oci"
bucket = "squared-005"

  [cloudStorage.credential]
  region = "us-phoenix-1"
  namespace = "abcdefghijkl"
  accessKeyId = "**********"
  secretAccessKey = "**********"
